### ISSUE TITLE
cupy_fft notebook doesn't use GPU

### ISSUE THREAD

**Issue by maxim-belkin** [maxim-belkin/how_to_gpu_in_python#7]
@kc9qey, `cupy_fft` notebook currently doesn't use GPUs (no calls to `cupy.cuda`). We also need to do the classic stuff -- compare the results of GPU and CPU calculations.

**Comment by kc9qey** [comment]
You are welcome to provide more examples.

Enviado desde mi iPhone

**Comment by kc9qey** [comment]
code runs on xk node with gpu, fails without gpu , note the cupy.asarray call https://docs.cupy.dev/en/stable/reference/generated/cupy.asarray.html https://docs.cupy.dev/en/stable/reference/generated/cupy.asnumpy.html

**Comment by kc9qey** [comment]
Show me how the code runs without cuda and a gpu .  Don't change the code.  :)

**Comment by kc9qey** [comment]
> @kc9qey, `cupy_fft` notebook currently doesn't use GPUs (no calls to `cupy.cuda`). We also need to do the classic stuff -- compare the results of GPU and CPU calculations.

The code fails on a cpu-only node and works with a gpu node.

**Comment by maxim-belkin** [comment]
> The code fails on a cpu-only node and works with a gpu node.

Right... so, I was worried about not using `cupy.cuda` calls but I see that we do use GPUs regardless of that.

I think this is a nice (1D) FFT example. We can get rid of the  `cupy.asarray()` call and replace `cupy.asnumpy()` with `.get()` method to make the data transfer step obvious:

```python
import cupy
import matplotlib.pyplot as plt

func = cupy.sin( cupy.arange(128) )

sp_gpu = cupy.fft.fft(func)
freq_gpu = cupy.fft.fftfreq(func.shape[-1])

sp = sp_gpu.get()
freq = freq_gpu.get()

plt.plot(freq, sp.real, freq, sp.imag)
plt.show()
```

What does `sp` stand for?
